### ISSUE TITLE
EMC_post_refactor to EMC_post/develop

### ISSUE THREAD

**Issue by JesseMeng-NOAA** [NOAA-EMC/UPP#174]
Phase 1 of refactor of remove goto remove grib1

**Comment by JesseMeng-NOAA** [comment]
Merge refactor phase 1 remove goto remove grib1 to EMC_post/develop

**Comment by WenMeng-NOAA** [comment]
Wen imported Jesse's branch merging branch "develop" under Wen's fork and renamed as "post_refactor_p1". Bo will commit new changes related to goto statement in this new branch.

**Comment by WenMeng-NOAA** [comment]
Kate's comments about grib1:
Grib1 removal comments:

Basic removal of grib1 if statements and calls to GRIBIT look ok to me
Do we need to keep the ID( ) array in the code?
Suggest removing other commented calls to GRIBIT and grib1 references
Should the GRIBIT routine itself be removed as well to keep code clean? Should perhaps at least remove from makefiles?
Consider adding more informative print statement in WRFPOST in case user tries grib1 for output format since it is now automatically set to grib2 without user knowing it.

**Comment by WenMeng-NOAA** [comment]
The UPP refactor phase 1 merge was submitted in the PR #196 and integrated in the develop at eed90d5 on 11/5/2020.

**Comment by WenMeng-NOAA** [comment]
The list of routines with goto statement changes can be found at
https://docs.google.com/spreadsheets/d/1JrMWKoEK680M0niWKfkgWW22D4mY-oyjGxOVxNvhvlQ/edit#gid=0

**Comment by fossell** [comment]
Regarding my comments on grib1 removal...was there any discussion about removing the ID() arrays from the code to clean up a bit more since those are only used for grib1?

**Comment by JesseMeng-NOAA** [comment]
Kate,

In some subroutines, e.g., MDLFLD.f, ID() arrays are used to calculate time
intervals and those are kept.
Others were cleaned up.
Thanks,

Jesse
==============================================
Dr. Jesse Meng
IMSG at NOAA/NWS/NCEP/EMC
5830 University Research Ct. Room 2037
College Park, MD 20740
email: jesse.meng@noaa.gov
==============================================

**Comment by WenMeng-NOAA** [comment]
@fossell Jesse made some changes based on your comments and combined with the PR #196. Please let us know if you have more comments.
