### ISSUE TITLE
Clean up remaining Grib1 files and code

### ISSUE THREAD

**Issue by fossell** [NOAA-EMC/UPP#344]
A few clean up issues to be addressed as discussed by code managers:

- [x] Remove grib1 .parm files from parm/ directory
- [ ] Remove grib1 parameters from RQSTFLD.f routine

**Comment by hertneky** [comment]
@WenMeng-NOAA I have started working on this cleanup task. The RQSTFLD.F routine can be completely removed, with some other minor code modifications. I have already removed 'IFILV' and 'AVBLGRB2' as they are not used anywhere in the code. The remaining variables 'AVBL' (grib1 char str), 'IQ' (grib1 param #), and 'IS' (grib1 lvl indicator) are only used by INITPOST_GFS_NEMS.f and INITPOST_GFS_SIGIO.f. Are these routines still in use by anyone or have they been fully deprecated? Can they be removed from being built and from the code? If they need to be retained, I will go the route of cleaning up those 2 I/O routines to remove references of AVBL/IQ/IS from them.

**Comment by WenMeng-NOAA** [comment]
@hertneky We will eventually remove the interfaces INITPOST_GFS_NEMS.f and INITPOST_GFS_SIGIO.f which are not used by any ops. applications any more. You might first try to remove them from the build script for your changes convenient. @HuiyaChuang-NOAA may chime in. Thanks!

**Comment by HuiyaChuang-NOAA** [comment]
@WenMeng-NOAA @hertneky I agree with Wen about removing INITPOST_GFS_NEMS.f and INITPOST_GFS_SIGIO.f as they're no longer used operationally

**Comment by hertneky** [comment]
@fossell @WenMeng-NOAA I am at a point in this process that a discussion will be useful in order to complete this task.

I have removed the body of RQSTFLDS.F and am left with a few remaining variables that are initialized in this routine. The options I see moving forward are:
1. Keep these variables in RQSTFLD.F (maybe rename this file to something more representative of what is left)
2. Move these variables to another routine that makes sense

Here are the variables that are initialized in RQSTFLD.F and used in at least 1 UPP routine.
MXFLD=999
- used in SET_OUTFLDS.f, RQSTFLD.F itself to allocate some vars
MXLVL=500
- used in getlvls.f, READ_xml.f, SET_LVLSXML.f, SET_OUTFLDS.f (commented), xml_perl_data.f
DATSET
- used in get_postfilename.f, SET_OUTFLDS.f
RITEHD
- used in get_postfilename.f, SET_OUTFLDS.f
NFLD
- used in SET_OUTFLDS.f
IGET(MXFLD)
- used everywhere
LVLS(MXLVL,MXFLD)
- used everywhere
IDENT(MXFLD)
- used in getlvls.f, SET_OUTFLDS.f
IAVBLFLD(MXFLD)
- used everywhere
ID(25)
- used everywhere
num_post_afld
- used in READ_xml.f, xml_perl_data.f, SET_OUTFLDS.f (commented)
LVLSXML(:,:)
- used everywhere

I have removed READCNTRL.f, INITPOST_GFS_SIGIO.f. The build with my latest mods is successful and a simple regression test of GFSv16 on NCARs Cheyenne showed no changed results.
