### ISSUE TITLE
Wrong values in grib2 files' land mask over sea ice

### ISSUE THREAD

**Issue by LydiaStefanova-NOAA** [NOAA-EMC/UPP#405]
In grib2 files from the coupled ufs-weather-model, the land mask has values of 2 along the contour of the sea ice region, and values of 0 in its interior. 

The grib2 files should either have values of 2 in all of the areas with sea ice or no values of 2 at all. 

An example grib2 file with this problem is here: 

_/scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/upp_issues/gfs.20130701/00/atmos/gfs.t00z.sfluxgrbf006.grib2_

For comparison, the land mask in the corresponding netcdf file has values of 2 for all sea ice and is 0 only for ice-free ocean. The netcdf file example is here:

_/scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/upp_issues/gfs.20130701/00/atmos/gfs.t00z.sfcf006.nc_

The problematic grib2 mask (left) and the corresponding netcdf mask (right) are shown below:

![image](https://user-images.githubusercontent.com/48454097/137355226-80fc2356-f6ef-4e13-8b68-b66819cd6984.png)

**Comment by HuiyaChuang-NOAA** [comment]
Investigation by post team indicated UPP identified a grid point is land when sea ice is larger than 0.1.  This works
when sea ice is binary.  However, recent change for the coupling team to use fractional ice rendered this logic invalid.
Wen updated UPP to use "0" as sea ice threshold instead of ".1" and this fixed the issue (see attached plot).

![GFS_landmask](https://user-images.githubusercontent.com/56728916/143134021-1a16ccd7-c3d3-447e-abb2-80171779e390.PNG)
