### ISSUE TITLE
release/public-v8: Delete old makefiles

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UPP#88]
Public release branch is using cmake. Old makefiles should be deleted.
```
makefile
makefile_dtc
makefile_lib
makefile_LINUX
makefile_Linux_gnu
makefile_Linux_intel
makefile_Linux_pgi
makefile_module
makefile_nems
makefile.sh
makefile_wcoss
```

**Comment by fossell** [comment]
@DusanJovic-NOAA - while some of these may be old and not used for any application, others are necessary for building EMC_post in a standalone manner or for operational use (e.g. makefile, makefile_dtc, makefile_module).  Our vision is that we will support standalone versions of UPP from release/public-v* branches so that community can use the same code within and outside any UFS app.  Even if we don't do that, my preference would be that we retain makefiles required for community and operational use, even if not used by UFS apps, so that the repo and all its branches can remain in sync.  This is will help facilitate code community code contributions in the future as well.  
@WenMeng-NOAA - Do you agree?

**Comment by WenMeng-NOAA** [comment]
I agree with @fossell. Right now we use makefile_module to build UPP executable for our UPP standalone test. The makefile_module is also used by ops. and emc gfs workflow and other application's workflow. The makefile_lib is used for building post library. We might delete some obsolete makefile from Dusan's list.

**Comment by DusanJovic-NOAA** [comment]
I'm talking about release/public-v8 branch which is not used in production. Is emc gfs workflow using this branch?

**Comment by fossell** [comment]
@DusanJovic-NOAA Yes I understand you mean just release/public-v8 branch, but removing all of them means that a user will not be able to build that branch outside of the app.  While that's ok right now, future vision is to have that possibility.  
Most importantly though, I do not think it is wise to let release/public-v8 branch diverge from develop in this manner.  This will not be consistent with our code management plan.  

I would ok removing the following makefiles with @WenMeng-NOAA's approval as well:
makefile_nems
makefile.sh
makefile_wcoss
makefile_LINUX
makefile_Linux_gnu
makefile_Linux_intel
makefile_Linux_pgi

But these makefiles should remain:
makefile_dtc
makefile_lib
makefile_module

**Comment by WenMeng-NOAA** [comment]
The emc gfs workflow does not use release/public-v8. If you keep makefile_module and makefile_lib, it would be good for me to run UPP standalone test for trouble-shooting UPP related issues.

**Comment by WenMeng-NOAA** [comment]
@fossell 's proposal makes sense to me.

**Comment by DusanJovic-NOAA** [comment]
Fixed in https://github.com/NOAA-EMC/EMC_post/commit/3f8a4b888f00f4e1576fb91f5697b225f8d9434c
